### ISSUE TITLE
Validation metrics error in Segmentation

### ISSUE THREAD

**Issue by guillemdelgado** [ComputerVisionCentre/mcv-m5#6]
Hello, we are Team 1 and we are having issues when calculating the metrics of the validation set using the provided model and the provided config file. We reviewed the code but we cannot find the error. Did anyone have the same problem and was able to solve it? Was anyone able to run the baseline without any problems?

We are having the following log:

 >  Training finished.

 > Testing the model...

 > Loading model from ./Experiments/camvid/proba1_Guillem/weights.hdf5
   Testing time: 10.5027060509. FPS: 22.2799723106. Seconds per Frame: 0.0448833591918
   Test metrics: 
      acc: 0.641700183446
      loss: 0.999698792426
      jaccard_coef: 0.246825623906
Traceback (most recent call last):
  File "train.py", line 124, in <module>
    main()
  File "train.py", line 116, in main
    process(cf)
  File "train.py", line 45, in process
    if (valid_gen != None): model.test(valid_gen)
  File "/home/master/mcv-m5/code/models/model.py", line 235, in test
    I[i] = metrics_dict['I'+str(i)]
KeyError: 'I0'
master@mastergpu01:~/mcv-m5/code$

**Comment by lluisgomez** [comment]
Hi guillem,
the error you are getting comes from a part of the code that is not necessary. you can comment lines from 228 to 243 in file models/model.py to skip it.
Sorry for any inconvenience.
